### ISSUE TITLE
Does this supports liblouis?

### ISSUE THREAD

**Issue by moyanming** [Keithcat1/nvda-controller-dart#2]
Hi,
Does your Flutter package support liblouis [https://github.com/liblouis/liblouis] API?
BTW, NVDA has already integrated the liblouis to support Braille translation.

**Comment by Keithcat1** [comment]
No. As implied by the name, it only supports NVDA controller. That's all I wanted to use, so that's all I wrapped and that's unlikely to change as far as I know.

**Comment by moyanming** [comment]
Thanks for the reply.

Any plan to make a new Flutter package of Liblouis? There is no Liblouis package in the pub yet.

**Comment by Keithcat1** [comment]
No plans to.
